from typing import Optional
from pathlib import Path
from functools import cached_property

from loguru import logger
import numpy as np
from numpy.typing import NDArray
from sentence_transformers import SentenceTransformer
from sentence_transformers.cross_encoder import CrossEncoder
from transformers import AutoTokenizer

from .base import SingletonMeta

from services import settings


class EmbeddingModelSingleton(metaclass=SingletonMeta):
    """
    A singletom class that provides a pre_trained transformer model for
    generation embeddings for the input text
    """

    def __init__(
        self,
        embedding_model_id: str = settings.TEXT_EMBEDDING_MODEL_ID,
        device: str = settings.RAG_MODEL_DEVICE,
        cach_dir: Optional[Path] = None,
    ) -> None:
        self.embedding_model_id = embedding_model_id
        self.device = device

        self._model = SentenceTransformer(
            self.embedding_model_id,
            device=self.device,  # "cpu" or "cuda"
            cache_folder=str(cach_dir)
            if cach_dir
            else None,  # where to store downloaded weights
        )

        self._model.eval()  # disables dropout, no gradient tracking

    @property
    def model_id(self) -> str:
        """
        Returns the identifier of the pre-trained transformer model to use.

        Returns:
            str: The identifier of the pre-trained transformer model to use.
        """

        return self.embedding_model_id

    @cached_property
    def embedding_size(self) -> int:
        """
        Returns the size of the embeddings generated by the pre-trained transformer model.

        Returns:
            int: The size of the embeddings generated by the pre-trained transformer model.
        """

        dummy_embedding = self._model.encode("")

        return dummy_embedding.shape[0]

    @property
    def max_input_length(self) -> int:
        """
        Returns the maximum length of input text to tokenize.

        Returns:
            int: The maximum length of input text to tokenize.
        """

        return self._model.max_seq_length

    @property
    def tokenizer(self) -> AutoTokenizer:
        """
        Returns the tokenizer used to tokenize input text.

        Returns:
            AutoTokenizer: The tokenizer used to tokenize input text.
        """

        return self._model.tokenizer

    def __call__(
        self, input_text: str | list[str], to_list: bool = True
    ) -> NDArray[np.float32] | list[float] | list[list[float]]:
        """
        Generate the embedding for the input text usinf the pre-trained transformer

        Args:
            input_text (str): The input text to generate embeddings for.
            to_list (bool): Whether to return the embeddings as a list or numpy array. Defaults to True.

        Returns:
            Union[np.ndarray, list]: The embeddings generated for the input text.
        """
        try:
            embeddings = self._model.encode(input_text)
        except Exception:
            logger.info(
                f"Error generating embedding for {self.embedding_model_id} and {input_text=}"
            )

            return [] if to_list else np.array([])

        if to_list:
            embeddings = embeddings.tolist()

        return embeddings


class CrossEncoderModelSingleton(metaclass=SingletonMeta):
    def __init__(
        self,
        embedding_model_id: str = settings.TEXT_EMBEDDING_MODEL_ID,
        device: str = settings.RAG_MODEL_DEVICE,
    ) -> None:
        """
        A singleton class that provides a pre-trained cross-encoder model for scoring pairs of input text.
        """

        self.embedding_model_id = embedding_model_id
        self.device = device

        self._model = CrossEncoder(
            model_name=self.embedding_model_id,
            device=self.device,
        )
        self._model.model.eval()

    def __call__(
        self, pairs: list[tuple[str, str]], to_list: bool = True
    ) -> NDArray[np.float32] | list[float]:
        scores = self._model.predict(pairs)

        if to_list:
            scores = scores.tolist()

        return scores
